/**
 * DATA.JS — Dados locais do site Chá de Casa Nova (Vitória & Rodrigo)
 */

// ============================================
// DADOS DOS PRESENTES
// ============================================
const PRESENTES_DATA = [
  {
    id: 1,
    nome: "Air Fryer Philco 5,5L",
    categoria: "eletros",
    preco: 549.90,
    status: "disponivel", // disponivel | reservado | parcial
    progresso: 80,
    quantidadeEscolhida: 8,
    descricao: "Perfeita para facilitar nosso dia a dia e preparar receitas deliciosas com mais praticidade e saúde.",
    textoEmocional: "Esse item fará parte dos nossos primeiros cafés da manhã juntos.",
    imagem: "https://images.unsplash.com/photo-1621972750749-0fbb1abb7736?auto=format&fit=crop&w=400&q=80",
    destaque: true,
    desejo: true,
  },
  {
    id: 2,
    nome: "Jogo de Panelas Inox",
    categoria: "cozinha",
    preco: 499.90,
    status: "disponivel",
    progresso: 0,
    quantidadeEscolhida: 0,
    descricao: "Conjunto completo com 5 peças em aço inoxidável, perfeito para cozinhar com amor.",
    textoEmocional: "Com essas panelas, cada refeição será preparada com todo carinho do mundo.",
    imagem: "https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?auto=format&fit=crop&w=400&q=80",
    destaque: true,
    desejo: false,
  },
  {
    id: 3,
    nome: "Liquidificador Pro 1200W",
    categoria: "eletros",
    preco: 329.90,
    status: "reservado",
    progresso: 100,
    quantidadeEscolhida: 1,
    descricao: "Potente e silencioso, ideal para vitaminas e receitas especiais nas manhãs do nosso novo lar.",
    textoEmocional: "As manhãs no nosso novo lar serão muito mais saborosas com ele.",
    imagem: "https://images.unsplash.com/photo-1578643463396-0997cb5328c1?auto=format&fit=crop&w=400&q=80",
    destaque: false,
    desejo: false,
  },
  {
    id: 4,
    nome: "Sofá 3 Lugares Veludo",
    categoria: "sala",
    preco: 2299.00,
    status: "parcial",
    progresso: 45,
    quantidadeEscolhida: 4,
    descricao: "Sofá elegante em veludo com design moderno, onde vamos passar nossos melhores momentos juntos.",
    textoEmocional: "É nele que vai acontecer nossos filmes e conversas mais especiais.",
    imagem: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=400&q=80",
    destaque: true,
    desejo: true,
  },
  {
    id: 5,
    nome: "Jogo de Pratos 12 peças",
    categoria: "cozinha",
    preco: 219.90,
    status: "disponivel",
    progresso: 0,
    quantidadeEscolhida: 0,
    descricao: "Aparelho de jantar em porcelana branca, perfeito para as nossas recepções com família e amigos.",
    textoEmocional: "Com esses pratos, cada jantar vai se tornar uma memória especial.",
    imagem: "https://images.unsplash.com/photo-1610701596007-11502861dcfa?auto=format&fit=crop&w=400&q=80",
    destaque: false,
    desejo: false,
  },
  {
    id: 6,
    nome: "Aspirador de Pó Robot",
    categoria: "eletros",
    preco: 389.90,
    status: "disponivel",
    progresso: 0,
    quantidadeEscolhida: 0,
    descricao: "Aspirador inteligente que mantém nossa casa sempre limpa enquanto aproveitamos o tempo juntos.",
    textoEmocional: "Vai nos ajudar a cuidar do nosso lar com muito mais praticidade.",
    imagem: "https://images.unsplash.com/photo-1575654402688-825595f9c54e?auto=format&fit=crop&w=400&q=80",
    destaque: false,
    desejo: false,
  },
  {
    id: 7,
    nome: "Jogo de Cama Queen Premium",
    categoria: "quarto",
    preco: 289.90,
    status: "disponivel",
    progresso: 0,
    quantidadeEscolhida: 0,
    descricao: "Lençol de algodão egípcio 400 fios, para noites de sono aconchegante e especial no nosso novo lar.",
    textoEmocional: "Para noites cheias de aconchego no nosso cantinho.",
    imagem: "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&w=400&q=80",
    destaque: true,
    desejo: false,
  },
  {
    id: 8,
    nome: "Cafeteira Italiana Espresso",
    categoria: "cozinha",
    preco: 189.90,
    status: "disponivel",
    progresso: 0,
    quantidadeEscolhida: 0,
    descricao: "Para os cafés da manhã especiais e aquele momento tranquilo de dois.",
    textoEmocional: "O cheiro do café vai ser a nossa memória favorita da manhã.",
    imagem: "https://images.unsplash.com/photo-1517701604599-bb29b565090c?auto=format&fit=crop&w=400&q=80",
    destaque: false,
    desejo: true,
  },
  {
    id: 9,
    nome: "Quadro Decorativo Canvas",
    categoria: "decoracao",
    preco: 159.90,
    status: "disponivel",
    progresso: 0,
    quantidadeEscolhida: 0,
    descricao: "Arte minimalista para decorar nossa sala com elegância e personalidade.",
    textoEmocional: "Cada detalhe na decoração conta um pouco da nossa história.",
    imagem: "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=400&q=80",
    destaque: false,
    desejo: false,
  },
  {
    id: 10,
    nome: "Jogo de Toalhas de Banho",
    categoria: "banheiro",
    preco: 149.90,
    status: "disponivel",
    progresso: 0,
    quantidadeEscolhida: 0,
    descricao: "Kit completo com 8 peças em algodão de alta qualidade, fofas e macias.",
    textoEmocional: "Pequenos confortos que fazem um lar ser especial.",
    imagem: "https://images.unsplash.com/photo-1616627547584-bf28cee262db?auto=format&fit=crop&w=400&q=80",
    destaque: false,
    desejo: false,
  },
  {
    id: 11,
    nome: "Vaso Decorativo Cerâmica",
    categoria: "decoracao",
    preco: 129.90,
    status: "disponivel",
    progresso: 0,
    quantidadeEscolhida: 0,
    descricao: "Vaso artesanal em cerâmica para trazer vida e calor ao ambiente.",
    textoEmocional: "Uma planta bonita e um vaso com alma vão completar nosso lar.",
    imagem: "https://images.unsplash.com/photo-1612196808214-b8e1d6145a8c?auto=format&fit=crop&w=400&q=80",
    destaque: false,
    desejo: false,
  },
  {
    id: 12,
    nome: "Mixer de Imersão 800W",
    categoria: "cozinha",
    preco: 169.90,
    status: "disponivel",
    progresso: 0,
    quantidadeEscolhida: 0,
    descricao: "Perfeito para sopas, vitaminas e molhos com praticidade e eficiência.",
    textoEmocional: "Para as sopas de inverno quentinhas que vamos fazer juntos.",
    imagem: "https://images.unsplash.com/photo-1574269909862-7e1d70bb8078?auto=format&fit=crop&w=400&q=80",
    destaque: false,
    desejo: false,
  },
];

// ============================================
// DADOS DOS RECADOS (mensagens iniciais)
// ============================================
const RECADOS_INICIAIS = [
  {
    id: 1,
    nome: "Família Silva",
    mensagem: "Que a nova casa seja sempre o lugar mais feliz do mundo pra vocês dois! Com muito amor!",
    data: "12 Jan 2026",
  },
  {
    id: 2,
    nome: "Carla & Rodrigo",
    mensagem: "Que este novo lar seja cheio de amor, risadas e muitas memórias lindas. Vocês merecem tudo!",
    data: "14 Jan 2026",
  },
  {
    id: 3,
    nome: "Vovó Maria",
    mensagem: "Meu coração está cheio de alegria por esse momento especial. Que Deus abençoe muito esse lar!",
    data: "15 Jan 2026",
  },
  {
    id: 4,
    nome: "Turma da faculdade",
    mensagem: "Vida longa e próspera para vocês! Mal podemos esperar pra conhecer o novo lar ✨",
    data: "18 Jan 2026",
  },
];

// ============================================
// CONFIGURAÇÕES DO SITE
// Edite para personalizar
// ============================================
const CONFIG = {
  nomes: "Vitória & Rodrigo",
  nomeA: "Vitória",
  nomeB: "Rodrigo",
  dataEvento: "27 de junho de 2026",
  localEvento: "Maceió, Alagoas",
  pixKey: "vitoriaerodrigo@email.com",
  whatsapp: "5582999990000",
  instagram: "@vitoriaerodrigo",
  endereco: "Rua das Palmeiras, 789 – Ponta Verde, Maceió, AL",
  itemsPerPage: 8,
};
